---
- name: Ensure charts directory exists
  file:
    path: "{{ ansible_env.HOME }}/charts"
    state: directory
    

- name: add metal3-deploy chart contents to metal3-deply in charts dir
  become: yes
  ansible.builtin.shell: sudo mv {{ ansible_env.HOME }}/baremetal/charts/metal3-deploy/0.1.0 {{ ansible_env.HOME }}/charts/metal3-deploy
        
- name: Find 
  find:
    paths: "{{ ansible_env.HOME }}/charts/metal3-deploy/charts"
    file_type: directory
  register: dirs
  
- name: Create symbolic links
  file:
    src: "{{ item.path }}"
    dest: "{{ ansible_env.HOME }}/charts/{{ item.path | basename }}"
    state: link
  with_items: "{{ dirs.files }}"
  when: item.path | basename not in ['nfs-subdir-external-provisioner', 'external-dns']
  
# - name: Create symbolic links
#   file:
#     src: "{{ item.path }}"
#     dest: "~/charts/{{ item.path | basename }}"
#     state: link
#   with_items: "{{ dirs.files }}"