---
# NOTE(gyee): we'll only include the first one that matches. The rest will be ignored.
- name: Include OS family vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
    - "main.yml"

- name: Include OS distribution vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower | replace(' ', '_') }}.yml"
    - "{{ ansible_distribution | replace(' ', '_') }}.yml"
    - "main.yml"

- name: Include platform-specific common tasks
  include_tasks: "_{{ ansible_os_family | lower }}.yml"

- name: Install python-ironicclient package
  become: yes
  pip:
    name: [pip, python-ironicclient]
    state: latest

- name: Create ~/.config/openstack
  file:
    path: ~/.config/openstack
    state: directory
    recurse: yes

- name: Copy clouds.yaml
  template:
    src: clouds.yaml.j2
    dest: ~/.config/openstack/clouds.yaml

- name: Set OS_CLOUD env var
  lineinfile:
    path: ~/.bashrc
    line: export OS_CLOUD=metal3
