---
- name: Install helm
  become: yes
  unarchive:
    src: "{{ helm_download_archive }}"
    dest: /usr/local/bin/
    include: [linux-amd64/helm]
    owner: root
    group: root
    remote_src: yes
    extra_opts:
     - --strip-components=1
  retries: 5
  delay: 5

- name: Install kubectl
  become: yes
  community.general.snap:
    name: kubectl
    classic: yes

- name: Install k9s
  become: yes
  unarchive:
    src: "{{ k9s_download_archive }}"
    dest: /usr/local/bin/
    include: [k9s]
    owner: root
    group: root
    remote_src: yes
  retries: 5
  delay: 5

- name: Install kustomize
  become: yes
  unarchive:
    src: "{{ kustomize_download_archive }}"
    dest: /usr/local/bin/
    include: [kustomize]
    owner: root
    group: root
    remote_src: yes
  retries: 5
  delay: 5

# per https://github.com/johanhaleby/kubetail#installation
- name: Install kubetail
  get_url:
    url: "{{ kubetail_download_url }}"
    dest: ~/bin/kubetail
    mode: 0755

- name: Check to see if krew is installed
  shell: >
    kubectl krew 2>&1
  register: kubectl_krew_result
  failed_when: kubectl_krew_result.rc > 1

# install krew per https://krew.sigs.k8s.io/docs/user-guide/setup/install/
- name: Install krew
  shell: >
    set -x; cd "$(mktemp -d)" &&
    OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
    ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
    KREW="krew-${OS}_${ARCH}" &&
    curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
    tar zxvf "${KREW}.tar.gz" &&
    ./"${KREW}" install krew
  when: "'unknown command \"krew\"' in kubectl_krew_result.stdout"

- name: Add $HOME/.krew/bin to PATH
  lineinfile:
    path: ~/.bashrc
    line: export PATH="$HOME/.krew/bin:$PATH"

# see https://cluster-api.sigs.k8s.io/user/quick-start.html#install-clusterctl
- name: Install clusterctl
  become: yes
  get_url:
    url: "https://github.com/kubernetes-sigs/cluster-api/releases/download/{{ capi_core_version }}/clusterctl-linux-amd64"
    dest: /usr/local/bin/clusterctl
    mode: 0755
    owner: root
    group: root

# install flux CLI per https://fluxcd.io/flux/installation/#install-the-flux-cli
- name: Install flux CLI
  shell: >
    curl -s https://fluxcd.io/install.sh | sudo bash
