---
# NOTE(gyee): we'll only include the first one that matches. The rest will be ignored.
- name: Include OS family vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
    - "main.yml"

- name: Include OS distribution vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower | replace(' ', '_') }}.yml"
    - "{{ ansible_distribution | replace(' ', '_') }}.yml"
    - "main.yml"

- name: Include platform-specific common tasks
  include_tasks: "_{{ ansible_os_family | lower }}.yml"

- name: Checkout baremetal repo
  include_role:
    name: baremetal
    tasks_from: checkout_baremetal_repo

- name: Create irionic-dnsmasq overrides yaml file
  template:
    src: ironic-dnsmasq-only-overrides.yaml.j2
    dest: ~/ironic-dnsmasq-only-chart-overrides.yaml
  register: template_parent_overrides

- name: Deploy dnsmasq using helm
  shell: >-
    env HELM_EXPERIMENTAL_OCI=1 \
    helm upgrade --install heavy-metal-dnsmasq ironic \
      --create-namespace --namespace metal-cubed \
      --values ~/ironic-dnsmasq-only-chart-overrides.yaml \
      --atomic --timeout 20m
  args:
    chdir: ~/baremetal/helm-charts
