---
- name: Build sample partition image
  shell: >
    disk-image-create ubuntu baremetal dhcp-all-interfaces grub2 -o ubuntu-partition
  args:
    chdir: "{{ images_dir }}"
  register: build_partition_image_result
  until: build_partition_image_result.rc == 0
  retries: 5
  delay: 10

- name: Build sample whole disk image
  shell: >
    disk-image-create ubuntu vm dhcp-all-interfaces -o ubuntu-whole-disk
  args:
    chdir: "{{ images_dir }}"
  register: build_partition_image_result
  until: build_partition_image_result.rc == 0
  retries: 5
  delay: 10

- name: Build sample whole disk image for UEFI
  shell: >
    disk-image-create ubuntu vm block-device-efi dhcp-all-interfaces -o ubuntu-whole-disk-efi
  args:
    chdir: "{{ images_dir }}"
  register: build_partition_image_result
  until: build_partition_image_result.rc == 0
  retries: 5
  delay: 10
