---
# which DNS provider backend to use
external_dns_provider: pdns

# PowerDNS backend specific config settings
external_dns_provider_config:
  pdns:
    # PowerDNS API request URL
    # *Must match metal3-powerdns.service.ip*
    apiUrl: "http://{{ pdns_ip }}"

    # PowerDNS API request port
    # *Must match metal3-powerdns.powerdns.webserver.port*
    apiPort: "8081"

    # PowerDNS API request authentication key
    # *Must match metal3-powerdns.powerdns.webserver.port*
    apiKey: "{{ pdns_api_key }}"

